//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambiesoft.FolderConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ambiesoft.FolderConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} has wrong value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _0_HAS_WRONG_VALUE {
            get {
                return ResourceManager.GetString("_0_HAS_WRONG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is set more than twice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _0_IS_SET_TWICE {
            get {
                return ResourceManager.GetString("_0_IS_SET_TWICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must not include {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _0_MUST_NOT_INCLUDE_1 {
            get {
                return ResourceManager.GetString("_0_MUST_NOT_INCLUDE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appname must be specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string APPNAME_MUST_BE_SPECIFIED {
            get {
                return ResourceManager.GetString("APPNAME_MUST_BE_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaultpathtype must be 0,1,2 or 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEFAULTTYPE_MUST_BE_0123 {
            get {
                return ResourceManager.GetString("DEFAULTTYPE_MUST_BE_0123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder must not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FOLDER_MUST_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FOLDER_MUST_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save folder settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FOLDER_SETTINGS_SAVEFAILED {
            get {
                return ResourceManager.GetString("FOLDER_SETTINGS_SAVEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Succeeded to save folder settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FOLDER_SETTINGS_SAVEOK {
            get {
                return ResourceManager.GetString("FOLDER_SETTINGS_SAVEOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Appname: App name used as subfolder of Creator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_APPNAME {
            get {
                return ResourceManager.GetString("HELP_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creator: Creator name used as subfolder of roaming or local folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_CREATOR {
            get {
                return ResourceManager.GetString("HELP_CREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture: Culture string, (ex) &quot;ja-JP&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_CULTURE {
            get {
                return ResourceManager.GetString("HELP_CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaultpathtype: 0,1,2 or 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_DEFAULT_FILE {
            get {
                return ResourceManager.GetString("HELP_DEFAULT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaultpath0: Default relative path from exe-resident folder for pathtype of 0. (Default is Exe-resident folder) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_DEFAULT_PATH0 {
            get {
                return ResourceManager.GetString("HELP_DEFAULT_PATH0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaultpath3: Default full path for pathytpe of 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_DEFAULT_PATH3 {
            get {
                return ResourceManager.GetString("HELP_DEFAULT_PATH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inifile: filename user chosen data will be saved. (Default is folder.ini) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_INIFILE {
            get {
                return ResourceManager.GetString("HELP_INIFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nookmessage:does not show succeeded message. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_NOOKMESSAGE {
            get {
                return ResourceManager.GetString("HELP_NOOKMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section: Section name of config. (Default is &apos;Main&apos;) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_SECTION_NAME_OF_CONFIG {
            get {
                return ResourceManager.GetString("HELP_SECTION_NAME_OF_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title: Title shown in Titlebar. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP_TITLE {
            get {
                return ResourceManager.GetString("HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNKNOWN_OPTION {
            get {
                return ResourceManager.GetString("UNKNOWN_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string USAGE {
            get {
                return ResourceManager.GetString("USAGE", resourceCulture);
            }
        }
    }
}
